<?php

namespace AppBundle\Repository;

/**
 * AstuceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstuceRepository extends \Doctrine\ORM\EntityRepository
{
}
