<?php

namespace AppBundle\Repository;

/**
 * InterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExterneRepository extends \Doctrine\ORM\EntityRepository
{
}
