<?php

namespace AppBundle\Repository;

/**
 * InterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExterneRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Calcule du nombre de publications externes enregistrées
   *
   * Author: Delrodie AMOIKON
   * Date: 09/12/2017
   */
   public function getNombrePublicationExterne()
   {
       $qb = $this->createQueryBuilder('p')
           ->select('count(p.id)')
       ;

       $query = $qb->getQuery();

       $recup =  $query->getSingleScalarResult();

       // Si compteur est egal a 0 alors initialiser
       if ($recup < 10){
           $suffixe = $recup;
           return $code = '00'.$suffixe;
       }
       elseif ($recup < 100) {
         $suffixe = $recup;
         return $code = '0'.$suffixe;
       }
       else{
           return $code = $recup;
       }
   }
   
   /**
     * Les publications internes actives
     *
     * Author: Delrodie AMOIKON
     * Date: 09/02/2017
     * Since: v1.0
     */
     public function getExterne($offset, $limit)
     {
         $em = $this->getEntityManager();
         $qb = $em->createQuery('
             SELECT e
             FROM AppBundle:Externe e
             WHERE e.statut = :stat
             ORDER BY e.datedeb DESC
         ')
           ->setParameter('stat', 1)
           ->setFirstResult($offset)
           ->setMaxResults($limit)
         ;
         try {
             $result = $qb->getResult();

             return $result;

         } catch (NoResultException $e) {
             return $e;
         }
     }
}
