<?php

namespace AppBundle\Repository;

/**
 * PhotothequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotothequeRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Calcule du nombre d'albums enregistrés'
   *
   * Author: Delrodie AMOIKON
   * Date: 09/12/2017
   */
   public function getNombreAlbums()
   {
       $qb = $this->createQueryBuilder('p')
           ->select('count(p.id)')
       ;

       $query = $qb->getQuery();

       $recup =  $query->getSingleScalarResult();

       // Si compteur est egal a 0 alors initialiser
       if ($recup < 10){
           $suffixe = $recup ;
           return $code = '00'.$suffixe;
       }
       elseif ($recup < 100) {
         $suffixe = $recup ;
         return $code = '0'.$suffixe;
       }
       else{
           return $code = $recup;
       }
   }
}
